import { type Metadata } from 'next'
// import {
//   ClerkProvider,
//   SignInButton,
//   SignUpButton,
//   SignedIn,
//   SignedOut,
//   UserButton,
// } from '@clerk/nextjs'
import { ClerkProvider } from '@clerk/nextjs'
import { Geist, Geist_Mono, Ranchers } from 'next/font/google'
import './globals.css'
import { ConvexClientProvider } from './ConvexClientProvider'
import Sidebar from '@/components/sidebar'
import { Toaster } from 'sonner'
import Header from '@/components/ui/header'
// import { useEffect } from 'react'
// import { initLogRocket } from "../utils/logrocket";

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const ranchers = Ranchers({
  variable: '--font-ranchers',
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
    // initLogRocket();
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} ${ranchers.variable} antialiased`}>
          {/* <header className="flex justify-end items-center p-4 gap-4 h-16 bg-background">
            <h1>pressto</h1>
            <SignedOut>
              <SignInButton />
              <SignUpButton>
                <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton>
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header> */}
          <div className="flex h-[calc(100vh-4rem)]">
            {/* set these items to flex */}
              <Sidebar />
            <div className="flex flex-col h-full w-full">
              <Header/>
            <main className="flex-1 overflow-auto">
              <ConvexClientProvider>{children}</ConvexClientProvider>
            </main>
            </div>
          </div>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  )
}